# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'VKAuth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'VK-ios-sdk'
  # Pods for VKAuth

end
